### ISSUE TITLE
Slider without any min and max options should also let you select higher values

### ISSUE THREAD

**Issue by marcofugaro** [rreusser/control-panel-2#3]
Hi! I guess the slider was designed with the options as a second argument was because they are optional, so If I do something like this

```js
State.Slider(10)
```
or just

```js
10
```

![image](https://user-images.githubusercontent.com/7217420/61993384-7c01e900-b06b-11e9-9872-6b5e15e0f032.png)

a slider with a default min and max would be created.

Now by default `min` is 0 and `max` is the value itself.
However after using it I think it would be more useful if the default `max` would be the `value * 2`. As a user I often also want to increase the value.

I think this would be a more reasonable default, I am willing to do a PR if you agreee with me.

**Comment by rreusser** [comment]
Makes total sense. Agreed. If you'd like to file a PR it would be greatly appreciated! And I'd be glad to add you as a contributor to the project so that I don't hold you up. 🙇

**Comment by marcofugaro** [comment]
Sure! Thank you!
